name: SnapClean
options:
  bundleIdPrefix: com.snapclean
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "26.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    ENABLE_HARDENED_RUNTIME: YES
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
    COMBINE_HIDPI_IMAGES: YES
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

targets:
  SnapClean:
    type: application
    platform: macOS
    sources:
      - path: SnapClean
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.snapclean.app
        INFOPLIST_FILE: SnapClean/Info.plist
        CODE_SIGN_ENTITLEMENTS: SnapClean/SnapClean.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        PRODUCT_NAME: SnapClean
        PRODUCT_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: YES
        NOTARIZATION_API_TYPE: use.xcode.com
    info:
      path: SnapClean/Info.plist
      properties:
        CFBundleName: SnapClean
        CFBundleDisplayName: SnapClean
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        NSHumanReadableCopyright: Copyright © 2025 SnapClean. All rights reserved.
        NSMainStoryboardFile: ""
        NSPrincipalClass: NSApplication
        NSSystemExtensionUsageDescription: SnapClean needs screen recording access to capture screenshots.
        NSScreenCaptureDescription: SnapClean needs screen recording access to capture screenshots of your screen.
        LSApplicationCategoryType: "public.app-category.productivity"
        LSBackgroundOnly: false
        LSUIElement: false
        CFBundleURLTypes: []
        NSUserNotificationUsageDescription: SnapClean uses notifications to inform you about screenshot status.
    entitlements:
      path: SnapClean/SnapClean.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-only: true
        com.apple.security.files.downloads.read-write: true
        com.apple.security.network.client: true
